

import '../public/globals.css'
import { Inter } from 'next/font/google'
import { AuthContextProvider } from './context/AuthContext'
import { ToastContainer } from 'react-toastify'
import { NextAuthProvider } from './context/Provider'
import { Toaster } from 'react-hot-toast'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'New Babblr',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
          <NextAuthProvider>
            <Toaster />
            {children}
          </NextAuthProvider>
      
      </body>
    </html>
  );
}